module prx.backbone.rest {
    exports com.prx.backoffice;
    exports com.prx.backoffice.converter to spring.beans;
    exports com.prx.backoffice.loggers.config to spring.beans;
    exports com.prx.backoffice.loggers.services to spring.beans, spring.core;
    exports com.prx.backoffice.loggers.interceptor to spring.beans;
    exports com.prx.backoffice.util to spring.beans;
    exports com.prx.backoffice.v1.contacttypes.api to spring.beans;
    exports com.prx.backoffice.v1.contacttypes.mapper to spring.beans;
    exports com.prx.backoffice.v1.contacttypes.service to spring.beans;
    exports com.prx.backoffice.v1.people.api.controller to spring.beans;
    exports com.prx.backoffice.v1.people.service to spring.beans;
    exports com.prx.backoffice.v1.people.mapper to spring.beans;
    exports com.prx.backoffice.v1.users.api.controller to spring.beans, spring.web;
    exports com.prx.backoffice.v1.users.service to spring.beans;
    exports com.prx.backoffice.v1.users.api.to to spring.beans;
    exports com.prx.backoffice.v1.users.mapper to spring.beans;
    exports com.prx.backoffice.v1.contacts.api to spring.beans;
    exports com.prx.backoffice.v1.contacts.service to spring.beans;
    exports com.prx.backoffice.v1.contacts.mapper to spring.beans;
    exports com.prx.backoffice.v1.roles.api.controller to spring.beans, spring.web;
    exports com.prx.backoffice.v1.roles.service to spring.beans;
    exports com.prx.backoffice.v1.roles.api.to to com.fasterxml.jackson.databind;
    exports com.prx.backoffice.v1.roles.mapper to spring.beans;
    exports com.prx.backoffice.v1.features.api.controller to spring.beans, spring.web;
    exports com.prx.backoffice.v1.features.api.to to com.fasterxml.jackson.databind;
    exports com.prx.backoffice.v1.features.service to spring.beans;
    exports com.prx.backoffice.v1.features.mapper to spring.beans;
    exports com.prx.backoffice.v1.features.mapper.decorator to spring.beans;
    exports com.prx.backoffice.v1.report.api.controller to spring.beans, spring.web;
    exports com.prx.backoffice.v1.report.service.impl to spring.beans;
    requires prx.persistence;
    requires jakarta.inject;
    requires jakarta.xml.bind;
    requires jakarta.validation;
    requires com.fasterxml.jackson.databind;
    requires spring.core;
    requires spring.context;
    requires spring.webmvc;
    requires spring.web;
    requires org.apache.tomcat.embed.core;
    requires org.postgresql.jdbc;
    requires org.hibernate.orm.core;
    requires org.hibernate.validator;
    requires org.apache.httpcomponents.client5.httpclient5;
    requires spring.beans;
    requires org.slf4j;
    requires spring.boot;
    requires spring.boot.autoconfigure;
    requires spring.cloud.openfeign.core;
    requires spring.data.jpa;
    requires io.swagger.v3.oas.annotations;
    requires org.mapstruct;
    requires commons.lang;
    requires java.base;
    requires com.prx.commons;
    requires org.apache.poi.ooxml;
    opens com.prx.backoffice to spring.core;
    opens com.prx.backoffice.loggers.services to spring.beans, spring.core;
    opens com.prx.backoffice.util to spring.core;
    opens com.prx.backoffice.v1.contacts.mapper to spring.beans, spring.core;
    opens com.prx.backoffice.v1.contacts.service to spring.beans, spring.core;
    opens com.prx.backoffice.v1.contacts.api to spring.core;
    opens com.prx.backoffice.v1.contacts.api.to to spring.beans, spring.core;
    opens com.prx.backoffice.v1.users.mapper to spring.beans, spring.core;
    opens com.prx.backoffice.v1.users.service to spring.beans, spring.core;
    opens com.prx.backoffice.v1.users.api.controller to spring.core;
    opens com.prx.backoffice.v1.users.api.to to spring.beans, spring.core;
    opens com.prx.backoffice.v1.contacttypes.mapper to spring.beans, spring.core;
    opens com.prx.backoffice.v1.contacttypes.service to spring.beans, spring.core;
    opens com.prx.backoffice.v1.contacttypes.api to spring.core;
    opens com.prx.backoffice.v1.features.mapper to spring.beans, spring.core;
    opens com.prx.backoffice.v1.features.service to spring.beans, spring.core;
    opens com.prx.backoffice.v1.features.api.controller to spring.beans, spring.core;
    opens com.prx.backoffice.v1.features.api.to to spring.beans, spring.core;
    opens com.prx.backoffice.v1.people.mapper to spring.beans, spring.core;
    opens com.prx.backoffice.v1.people.service to spring.beans, spring.core;
    opens com.prx.backoffice.v1.people.api.controller to spring.core;
    opens com.prx.backoffice.v1.people.api.to to spring.beans, spring.core;
    opens com.prx.backoffice.v1.roles.mapper to spring.beans, spring.core;
    opens com.prx.backoffice.v1.roles.service to spring.beans, spring.core;
    opens com.prx.backoffice.v1.roles.api.controller to spring.core;
    opens com.prx.backoffice.v1.roles.api.to to spring.beans, spring.core;
    opens com.prx.backoffice.v1.report.api.controller to spring.core;
    exports com.prx.backoffice.enums.keys;

}
