-- =============================================================================
-- Migration : V1__create_audit_event.sql
-- Description: Creates the audit_event table used by AuditEventEntity to
--              record security-relevant user actions (login, password change,
--              role assignment, etc.) with full context metadata.
-- Schema     : public (PostgreSQL default)
-- Author     : backbone-rest / IAM Phase 2
-- Date       : 2026-05-30
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Event-type constraint enum
--    Declared as a CHECK list rather than a PG ENUM so that new values can be
--    added via ALTER TABLE without a full table rewrite.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS general.audit_event
(
    -- -----------------------------------------------------------------------
    -- Primary key — UUID v4, generated by the application layer (JPA / service)
    -- -----------------------------------------------------------------------
    id               UUID                        NOT NULL,

    -- -----------------------------------------------------------------------
    -- Foreign-key references (logical — not enforced here because the user /
    -- application entities live in a separate schema managed by the
    -- com.umdc.persistence module)
    -- -----------------------------------------------------------------------
    user_id          UUID                        NOT NULL,
    application_id   UUID                        NOT NULL,

    -- -----------------------------------------------------------------------
    -- Event classification
    -- Allowed values: LOGIN_SUCCESS, LOGIN_FAILURE, PASSWORD_CHANGE,
    --                 ROLE_ASSIGNED, ROLE_REVOKED, LOGOUT, ACCOUNT_LOCKED,
    --                 ACCOUNT_UNLOCKED, TOKEN_REFRESH, PASSWORD_RESET_REQUEST
    -- The CHECK constraint acts as a guard; extend the list here + in the
    --  AuditEventType enum without requiring a schema migration.
    -- -----------------------------------------------------------------------
    event_type       VARCHAR(64)                 NOT NULL
        CONSTRAINT audit_event_type_ck CHECK (
            event_type IN (
                'LOGIN_SUCCESS',
                'LOGIN_FAILURE',
                'PASSWORD_CHANGE',
                'ROLE_ASSIGNED',
                'ROLE_REVOKED',
                'LOGOUT',
                'ACCOUNT_LOCKED',
                'ACCOUNT_UNLOCKED',
                'TOKEN_REFRESH',
                'PASSWORD_RESET_REQUEST'
            )
        ),

    -- -----------------------------------------------------------------------
    -- Network context
    -- ip_address: supports both IPv4 (15 chars) and IPv6 (45 chars)
    -- user_agent: standard HTTP header — up to 512 chars to cover all common
    --             browser / mobile agent strings
    -- -----------------------------------------------------------------------
    ip_address       VARCHAR(45),
    user_agent       VARCHAR(512),

    -- -----------------------------------------------------------------------
    -- Timestamp — stored in UTC; application must pass UTC values.
    -- NOT NULL — every audit record must have an occurrence time.
    -- -----------------------------------------------------------------------
    occurred_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL
        DEFAULT (NOW() AT TIME ZONE 'UTC'),

    -- -----------------------------------------------------------------------
    -- Flexible detail payload — stored as JSONB for indexed querying.
    -- Examples: {"reason":"bad_password","attempt":3}
    --           {"role":"ADMIN","assigned_by":"00000000-..."}
    -- -----------------------------------------------------------------------
    details          JSONB,

    -- -----------------------------------------------------------------------
    -- Audit metadata (row-level housekeeping)
    -- -----------------------------------------------------------------------
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL
        DEFAULT (NOW() AT TIME ZONE 'UTC'),

    CONSTRAINT audit_event_pk PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------------
-- 2. Indexes
-- ---------------------------------------------------------------------------

-- Most common query: "show all events for this user"
CREATE INDEX IF NOT EXISTS idx_audit_event_user_id
    ON general.audit_event (user_id);

-- Filter by application
CREATE INDEX IF NOT EXISTS idx_audit_event_application_id
    ON general.audit_event (application_id);

-- Filter by event type (e.g. fetch all LOGIN_FAILURE in last 15 min)
CREATE INDEX IF NOT EXISTS idx_audit_event_event_type
    ON general.audit_event (event_type);

-- Time-range queries (most-recent-first is the dominant read pattern)
CREATE INDEX IF NOT EXISTS idx_audit_event_occurred_at
    ON general.audit_event (occurred_at DESC);

-- Composite: user + event_type + time — covers the brute-force lockout query:
--   "count LOGIN_FAILURE for user X in last N minutes"
CREATE INDEX IF NOT EXISTS idx_audit_event_user_type_time
    ON general.audit_event (user_id, event_type, occurred_at DESC);

-- Composite: application + event_type — covers per-app activity reports
CREATE INDEX IF NOT EXISTS idx_audit_event_app_type
    ON general.audit_event (application_id, event_type);

-- JSONB details — GIN index for operators @>, ?, ?|, ?&
CREATE INDEX IF NOT EXISTS idx_audit_event_details_gin
    ON general.audit_event USING GIN (details)
    WHERE details IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 3. Table + column comments (pg_catalog visible via \d+ in psql)
-- ---------------------------------------------------------------------------
COMMENT ON TABLE  general.audit_event                   IS 'Immutable security audit log — one row per user action.';
COMMENT ON COLUMN general.audit_event.id                IS 'UUID v4 primary key; generated by the application.';
COMMENT ON COLUMN general.audit_event.user_id           IS 'Logical FK → user entity (managed by com.umdc.persistence).';
COMMENT ON COLUMN general.audit_event.application_id    IS 'Logical FK → application entity.';
COMMENT ON COLUMN general.audit_event.event_type        IS 'Classifies the security event; see audit_event_type_ck.';
COMMENT ON COLUMN general.audit_event.ip_address        IS 'IPv4 or IPv6 source address of the request.';
COMMENT ON COLUMN general.audit_event.user_agent        IS 'HTTP User-Agent header value.';
COMMENT ON COLUMN general.audit_event.occurred_at       IS 'UTC timestamp when the event occurred.';
COMMENT ON COLUMN general.audit_event.details           IS 'JSONB bag of event-specific details (attempt count, role name, etc.).';
COMMENT ON COLUMN general.audit_event.created_at        IS 'UTC timestamp when the row was inserted.';

