-- =============================================================================
-- Migration : V2__create_managed_client.sql
-- Description: Creates the managed_client table used by ManagedClientEntity to
--              store application-to-application (M2M) credential registrations.
-- Schema     : public
-- Author     : backbone-rest / MCAM Phase 1
-- Date       : 2026-06-03
-- =============================================================================

CREATE TABLE IF NOT EXISTS general.managed_client
(
    -- -----------------------------------------------------------------------
    -- Primary key — UUID v4, generated by the application layer
    -- -----------------------------------------------------------------------
    id                      UUID         NOT NULL,

    -- -----------------------------------------------------------------------
    -- Identity
    -- -----------------------------------------------------------------------
    name                    VARCHAR(128) NOT NULL,
    description             VARCHAR(512),

    -- -----------------------------------------------------------------------
    -- Logical FK → application entity (managed by com.umdc.persistence)
    -- -----------------------------------------------------------------------
    application_id          UUID         NOT NULL,

    -- -----------------------------------------------------------------------
    -- Secret hashes — BCrypt encoded, strength >= 12.
    -- secret_hash      : current active secret hash
    -- prev_secret_hash : populated only during grace-period rotation
    -- -----------------------------------------------------------------------
    secret_hash             VARCHAR(255) NOT NULL,
    prev_secret_hash        VARCHAR(255),

    -- -----------------------------------------------------------------------
    -- Authorisation scopes stored as a native PostgreSQL TEXT[] array.
    -- -----------------------------------------------------------------------
    scopes                  TEXT[]       NOT NULL,

    -- -----------------------------------------------------------------------
    -- Lifecycle flags and timestamps
    -- -----------------------------------------------------------------------
    active                  BOOLEAN      NOT NULL DEFAULT true,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    last_updated_at         TIMESTAMPTZ,
    secret_last_rotated_at  TIMESTAMPTZ,

    CONSTRAINT managed_client_pk PRIMARY KEY (id),

    -- Uniqueness: a name must be unique within an application
    CONSTRAINT managed_client_name_app_uq UNIQUE (name, application_id)
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- Filter by owning application
CREATE INDEX IF NOT EXISTS idx_managed_client_application_id
    ON general.managed_client (application_id);

-- Filter by active flag (common admin query)
CREATE INDEX IF NOT EXISTS idx_managed_client_active
    ON general.managed_client (active);

-- Composite: application + active — covers paginated list with both filters
CREATE INDEX IF NOT EXISTS idx_managed_client_app_active
    ON general.managed_client (application_id, active);

-- ---------------------------------------------------------------------------
-- Table and column comments
-- ---------------------------------------------------------------------------
COMMENT ON TABLE  general.managed_client                        IS 'M2M managed client credential registrations for the MCAM feature.';
COMMENT ON COLUMN general.managed_client.id                     IS 'UUID v4 primary key; generated by the application.';
COMMENT ON COLUMN general.managed_client.name                   IS 'Human-readable name; unique within an application.';
COMMENT ON COLUMN general.managed_client.description            IS 'Optional description of the client purpose.';
COMMENT ON COLUMN general.managed_client.application_id         IS 'Logical FK → application entity (com.umdc.persistence).';
COMMENT ON COLUMN general.managed_client.secret_hash            IS 'BCrypt hash of the current client secret.';
COMMENT ON COLUMN general.managed_client.prev_secret_hash       IS 'BCrypt hash of the previous secret during rotation grace period.';
COMMENT ON COLUMN general.managed_client.scopes                 IS 'Authorised OAuth2 scopes as a PostgreSQL TEXT[] array.';
COMMENT ON COLUMN general.managed_client.active                 IS 'Whether the client is allowed to issue tokens.';
COMMENT ON COLUMN general.managed_client.created_at             IS 'UTC timestamp when the record was created.';
COMMENT ON COLUMN general.managed_client.last_updated_at        IS 'UTC timestamp of the last metadata update.';
COMMENT ON COLUMN general.managed_client.secret_last_rotated_at IS 'UTC timestamp of the most recent secret rotation.';

