-- =============================================================================
-- Migration : V3__create_managed_client_audit_event.sql
-- Description: Creates the managed_client_audit_event table for MCAM M2M
--              lifecycle audit records. Kept separate from audit_event so that
--              the user_id NOT NULL constraint on that table is not relaxed.
-- Schema     : public
-- Author     : backbone-rest / MCAM Phase 1
-- Date       : 2026-06-03
-- =============================================================================

CREATE TABLE IF NOT EXISTS general.managed_client_audit_event
(
    -- -----------------------------------------------------------------------
    -- Primary key — UUID v4, generated by the application layer
    -- -----------------------------------------------------------------------
    id          UUID        NOT NULL,

    -- -----------------------------------------------------------------------
    -- Logical FK → managed_client.id (not enforced at DB level to avoid
    -- cascading issues when clients are deleted)
    -- -----------------------------------------------------------------------
    client_id   UUID        NOT NULL,

    -- -----------------------------------------------------------------------
    -- Event classification — matches AuditEventType enum M2M values
    -- -----------------------------------------------------------------------
    event_type  VARCHAR(64) NOT NULL,

    -- -----------------------------------------------------------------------
    -- Network context (IPv4 / IPv6 max 45 chars)
    -- -----------------------------------------------------------------------
    ip_address  VARCHAR(45),

    -- -----------------------------------------------------------------------
    -- Outcome: 'SUCCESS' or 'FAILURE'
    -- -----------------------------------------------------------------------
    outcome     VARCHAR(16) NOT NULL,

    -- -----------------------------------------------------------------------
    -- Flexible JSONB detail payload
    -- -----------------------------------------------------------------------
    details     JSONB,

    -- -----------------------------------------------------------------------
    -- Timestamp — stored with time-zone; application passes UTC values
    -- -----------------------------------------------------------------------
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT managed_client_audit_event_pk PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- Most common query: "all events for a specific client"
CREATE INDEX IF NOT EXISTS idx_mcam_audit_client_id
    ON general.managed_client_audit_event (client_id);

-- Filter by event type
CREATE INDEX IF NOT EXISTS idx_mcam_audit_event_type
    ON general.managed_client_audit_event (event_type);

-- Time-range queries (most-recent-first read pattern)
CREATE INDEX IF NOT EXISTS idx_mcam_audit_occurred_at
    ON general.managed_client_audit_event (occurred_at DESC);

-- Composite: client + event_type — covers per-client filtered reports
CREATE INDEX IF NOT EXISTS idx_mcam_audit_client_event
    ON general.managed_client_audit_event (client_id, event_type);

-- ---------------------------------------------------------------------------
-- Table and column comments
-- ---------------------------------------------------------------------------
COMMENT ON TABLE  general.managed_client_audit_event            IS 'Append-only audit log for M2M managed client lifecycle events.';
COMMENT ON COLUMN general.managed_client_audit_event.id         IS 'UUID v4 primary key; generated by the application.';
COMMENT ON COLUMN general.managed_client_audit_event.client_id  IS 'Logical FK → managed_client.id.';
COMMENT ON COLUMN general.managed_client_audit_event.event_type IS 'M2M AuditEventType enum value (e.g. CLIENT_TOKEN_ISSUED).';
COMMENT ON COLUMN general.managed_client_audit_event.ip_address IS 'IPv4 or IPv6 source address of the request.';
COMMENT ON COLUMN general.managed_client_audit_event.outcome    IS 'Result of the action: SUCCESS or FAILURE.';
COMMENT ON COLUMN general.managed_client_audit_event.details    IS 'JSONB bag of event-specific details.';
COMMENT ON COLUMN general.managed_client_audit_event.occurred_at IS 'UTC timestamp when the event occurred.';

